apiVersion: v1
kind: Secret
metadata:
  name: sportiverse-webapi-secret
  namespace: sportiverse-namespace
type: Opaque
data:
  MONGODB_USERNAME: 'YWRtaW4=' # base64 encoded string for 'admin'
  MONGODB_PASSWORD: 'cGFzc3dvcmQ=' # base64 encoded string for 'password'
  JWT_SECRET: 'c3BvcnRpdmVyc2Utand0LXNlY3JldA==' # base64 encoded string for 'sportiverse-jwt-secret'
  PAYPAL_CLIENT_ID: 'QWYzdC1mdHZvaldxblp5TzVoRENZT1BOYURkTFY3M21zTlg5RFZGU3JFbVR2bnRsRTExMFlxTzZ3YWlmWGFDTWJPbGdER2V6OUh3cWxuUjk='
  PAYPAL_APP_SECRET: 'RUJYZGRXR05FdWM0akExeVJxbk9nOFN6SWJFRmdsMHFORnVfX0FMMlFqT2N0Z29YN0syeXo2S0FBdENBbDZQWHdhdjVKV3VHd1FQaXRsRGM='
  PAYPAL_API_URL: 'aHR0cHM6Ly9hcGktbS5zYW5kYm94LnBheXBhbC5jb20='
