apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sportiverse-namespace
  name: db-role
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get']
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get']
  - apiGroups: ['apps']
    resources: ['statefulsets']
    verbs: ['get', 'list', 'update']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-rolebinding
  namespace: sportiverse-namespace
subjects:
  - kind: ServiceAccount
    name: sportiverse-db-sa
    namespace: sportiverse-namespace
roleRef:
  kind: Role
  name: db-role
  apiGroup: rbac.authorization.k8s.io
