apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium # You can give it any name
provisioner: kubernetes.io/azure-disk # This is for Azure Disk (block storage)
parameters:
  skuname: Premium_LRS # Azure Storage type (Premium Managed Disks)
reclaimPolicy: Delete # Define how volumes should behave when released from PVC (Retain or Delete)
volumeBindingMode: WaitForFirstConsumer # Wait for the consumer (PVC) to be scheduled before provisioning
