apiVersion: v1
kind: Service
metadata:
  name: sportiverse-db-service
  namespace: sportiverse-namespace
spec:
  type: ClusterIP
  selector:
    app: sportiverse-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
# Database Nodeport service was created just to access the database from the host machine.
# This is useful when you are using on-premises infrastructure like Docker Desktop or Minikube.
# It is not recommended to use this service in production.

# apiVersion: v1
# kind: Service
# metadata:
#   name: sportiverse-db-nodeport-service
#   namespace: sportiverse-namespace
# spec:
#   type: NodePort
#   selector:
#     app: sportiverse-db
#   ports:
#     - protocol: TCP
#       port: 27017
#       targetPort: 27017
#       nodePort: 32017

---
# Database Loadbalancer service was created just to access the database from the host machine.
# This is useful when you are using cloud providers like AWS, Azure, or GCP.
# It is not recommended to use this service in production.

apiVersion: v1
kind: Service
metadata:
  name: sportiverse-db-loadbalancer-service
  namespace: sportiverse-namespace
spec:
  type: LoadBalancer
  selector:
    app: sportiverse-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
