apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportiverse-webapi-deployment
  namespace: sportiverse-namespace
  labels:
    app: sportiverse-webapi
spec:
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sportiverse-webapi
  template:
    metadata:
      labels:
        app: sportiverse-webapi
    spec:
      serviceAccountName: sportiverse-webapi-sa
      containers:
        - name: sportiverse-webapi-container
          image: prasadhonrao/sportiverse-webapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sportiverse-webapi-configmap
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sportiverse-webapi-configmap
                  key: MONGODB_PORT
            - name: MONGODB_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: sportiverse-webapi-configmap
                  key: MONGODB_DB_NAME
            - name: MONGODB_DB_PARAMS
              valueFrom:
                configMapKeyRef:
                  name: sportiverse-webapi-configmap
                  key: MONGODB_DB_PARAMS
            - name: PAGINATION_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: sportiverse-webapi-configmap
                  key: PAGINATION_LIMIT
            - name: UPLOAD_PATH
              valueFrom:
                configMapKeyRef:
                  name: sportiverse-webapi-configmap
                  key: UPLOAD_PATH
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sportiverse-webapi-secret
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sportiverse-webapi-secret
                  key: MONGODB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sportiverse-webapi-secret
                  key: JWT_SECRET
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sportiverse-webapi-secret
                  key: PAYPAL_CLIENT_ID
            - name: PAYPAL_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: sportiverse-webapi-secret
                  key: PAYPAL_APP_SECRET
            - name: PAYPAL_API_URL
              valueFrom:
                secretKeyRef:
                  name: sportiverse-webapi-secret
                  key: PAYPAL_API_URL
          resources:
            limits:
              memory: '2Gi'
              cpu: '2'
            requests:
              memory: '1Gi'
              cpu: '1'
      nodeSelector:
        kubernetes.io/os: linux
