apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sportiverse-namespace
  name: webapi-role
rules:
  - apiGroups: ['']
    resources: ['secrets', 'configmaps']
    verbs: ['get', 'list', 'create']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['list', 'get']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'create', 'update', 'patch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapi-rolebinding
  namespace: sportiverse-namespace
subjects:
  - kind: ServiceAccount
    name: sportiverse-webapi-sa
    namespace: sportiverse-namespace
roleRef:
  kind: Role
  name: webapi-role
  apiGroup: rbac.authorization.k8s.io
